name: Build

on:
  workflow_dispatch:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml/compiler: 5.1.1

      - Build:
        run: make

      - name: Rename Output
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv build/todo.exe todo-windows.exe
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            mv build/todo todo-macos
          else
            mv build/todo todo-linux
          fi

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            *.exe
            todo-linux
            todo-macos

